
# ??????? ,????????????
#server.port=80
server:
  port: 80
  servlet:
    context-path:
# ??banner,????????spring??
#spring.main.banner-mode=off

datasource:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost/test
  username: root
  password: 123456
# ???????
#logging.level.root=info

#?????
city: nanc
user:
  name:ljl
  age:18

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456